### ISSUE TITLE
Call video error get remote video of android

### ISSUE THREAD

**Issue by nguyenlv1108** [GetStream/stream-video-js#1458] opened 2024-08-09 14:11 UTC
**Which package/packages do you use?**

- [x] `@stream-io/video-react-native-sdk`

**Describe the bug**
When Android calls iPhone, both device turn on the microphone and the camera on the Android device can hear and see the iPhone, but on the iPhone device can hear but cannot see the video of android.

**To Reproduce**

1. android call iphone is ringing
2. iphone accept
3. iphone cannot get remote participant of android

**Expected behavior**
Both device can hear and see the video

**Version**

- latest version

**React Native**

- android galaxy a15 and iphone 12
- react native 0.72.6

**Comment by Ducnnnn** [comment] 2024-08-12 09:12
i same, ple fix it now.

**Comment by santhoshvai** [comment] 2024-08-12 14:00
@nguyenlv1108 I have tried this and I couldn't reproduce this. Can you also try on a different android device also please so that we can eliminate any device specific errors.

Also. on step 1, was iPhone on the background and the call was accepted from push notification?

**Comment by nguyenlv1108** [comment] 2024-08-13 14:23
@santhoshvai We use react-native-cli don't expo and dont use push notification.

IPhone use method getOrCreateVideo then android accept and join call finally android can see both camera but iphone only see itself camera

**Comment by santhoshvai** [comment] 2024-08-14 09:20
Hi, 

Once you call getOrCreate the call will automatically go to ringing state and you can get the object from `useCalls` in the screen you navigate to after and no need to accept for the caller. I hope this is clear to you. 

To make it simpler, I would advise to have a common screen in both callee and caller, where you can show incoming or outgoing call UI. Here is a simple implementation https://github.com/GetStream/stream-video-js/blob/main/sample-apps/react-native/expo-video-sample/app/ringing.tsx

**Comment by nguyenlv1108** [comment] 2024-08-14 11:21
Are you sure getOrCreate automatically ringing? we have tried many times but it doesn't work, we need to add option ring:true to listen call.ring to customize the layout again, in my code when iphone calls iphone everything is normal Normally, I get an error on Android

**Comment by santhoshvai** [comment] 2024-08-23 04:11
@nguyenlv1108 Sorry for the delay in getting back to you. 

**Caller side:**
For the user who does  ```await call.getOrCreate({ ring: true,  ... })``` the call will go into ringing mode.  Once the call is accepted by the accepted by the other user (callee). The call is then automatically joined. Soon after getOrCreate is done, you can move the app to the `RINGING_SCREEN_STACK` screen and there is no need to listen on `'call.ring'`

***Callee side:*
When there is an incoming call, the call arrives with a calling state of CallingState.RINGING, the callee can then do `call.join()` no need to call accept, as join will take care of it.

Inside the screen where you want to show the active call lets say, `RINGING_SCREEN_STACK`
you can use `useCalls` hook to get the call in the ringing state for example

` const calls = useCalls().filter(
    (c) => c.state.callingState === CallingState.RINGING,
  );`
  
 You can then pass the call into [RingingCallContent](https://getstream.io/video/docs/reactnative/ui-components/call/ringing-call-content/), it will take care of showing Incoming Call UI and Outgoing Call UI 
  
  ```
  return (
    <StreamCall call={call[0]}>
      <RingingCallContent />
    </StreamCall>
  );
  ```

**Comment by oliverlaz** [comment] 2024-09-03 11:20
hi @nguyenlv1108, I'm closing this issue as completed. Please feel free to reopen it in case you need more help.

**Closed by oliverlaz** 2024-09-03 11:20 UTC
Labels: react-native, support
